### ISSUE TITLE
Snippet inserted twice in static page

### ISSUE THREAD

**Issue by climao** [inetis-ch/oc-richeditorsnippets-plugin#12]
I have a plugin that registers components using registerPageSnippets().

I decided to install *Richeditor Snippets* to be able to add those snippets to blog post content, and I managed to do so without any problems.

However, after installing your plugin, when I try to use the snippets in static pages (by clicking on then) they are inserted **twice**.
Any ideas about what I might be doing wrong? Or is this any known problem?

**Comment by Fl0Cri** [comment]
Thanks for reporting this. We just made an update to fix this issue as well as other odd behaviors with RainLab Pages 1.3.5 (such as page tabs being open twice).
