### ISSUE TITLE
Snippets not editable in rich editors outside static pages after save

### ISSUE THREAD

**Issue by WC-Jordy** [inetis-ch/oc-richeditorsnippets-plugin#13]
I'd like to use snippets in a rich editor for a model. This is how it looks:

![image](https://user-images.githubusercontent.com/69194376/89279028-2b8e7580-d647-11ea-9db6-b5246dec3dde.png)

However, when I save the record, I cannot edit the snippet any longer. Because the attributes pop-up doesn't appear anymore.

How can this be fixed so they are editable after saves? Thanks in advance.

EDIT: This exclusively happens when you save the record while the attributes pop-up is active. While the pop-up is open, the snippet contains some extra CSS classes which also get stored in the record. The next time it opens up those classes are still there and the script thinks the attributes pop-up is active while it's not.

**Comment by Fl0Cri** [comment]
Wow, looks like you've found an issue with [StaticPages](https://github.com/rainlab/pages-plugin) ;-)

I could reproduce your problem using only Static Pages without RicheditorSnippets. I suggest you open an issue there and link to this one, I will put a comment to let them know at least 2 people could reproduce it.
